/*
Slurm REST API

API to access and control Slurm

API version: Slurm-24.05.5&openapi/slurmdbd&openapi/dbv0.0.39&openapi/slurmctld&openapi/v0.0.39
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the V0041OpenapiSlurmdbdJobsRespMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0041OpenapiSlurmdbdJobsRespMeta{}

// V0041OpenapiSlurmdbdJobsRespMeta Slurm meta values
type V0041OpenapiSlurmdbdJobsRespMeta struct {
	Plugin *V0040OpenapiMetaPlugin `json:"plugin,omitempty"`
	Client *V0040OpenapiMetaClient `json:"client,omitempty"`
	// CLI command (if applicable)
	Command []string `json:"command,omitempty"`
	Slurm *V0040OpenapiMetaSlurm `json:"slurm,omitempty"`
}

// NewV0041OpenapiSlurmdbdJobsRespMeta instantiates a new V0041OpenapiSlurmdbdJobsRespMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0041OpenapiSlurmdbdJobsRespMeta() *V0041OpenapiSlurmdbdJobsRespMeta {
	this := V0041OpenapiSlurmdbdJobsRespMeta{}
	return &this
}

// NewV0041OpenapiSlurmdbdJobsRespMetaWithDefaults instantiates a new V0041OpenapiSlurmdbdJobsRespMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0041OpenapiSlurmdbdJobsRespMetaWithDefaults() *V0041OpenapiSlurmdbdJobsRespMeta {
	this := V0041OpenapiSlurmdbdJobsRespMeta{}
	return &this
}

// GetPlugin returns the Plugin field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdJobsRespMeta) GetPlugin() V0040OpenapiMetaPlugin {
	if o == nil || IsNil(o.Plugin) {
		var ret V0040OpenapiMetaPlugin
		return ret
	}
	return *o.Plugin
}

// GetPluginOk returns a tuple with the Plugin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdJobsRespMeta) GetPluginOk() (*V0040OpenapiMetaPlugin, bool) {
	if o == nil || IsNil(o.Plugin) {
		return nil, false
	}
	return o.Plugin, true
}

// HasPlugin returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdJobsRespMeta) HasPlugin() bool {
	if o != nil && !IsNil(o.Plugin) {
		return true
	}

	return false
}

// SetPlugin gets a reference to the given V0040OpenapiMetaPlugin and assigns it to the Plugin field.
func (o *V0041OpenapiSlurmdbdJobsRespMeta) SetPlugin(v V0040OpenapiMetaPlugin) {
	o.Plugin = &v
}

// GetClient returns the Client field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdJobsRespMeta) GetClient() V0040OpenapiMetaClient {
	if o == nil || IsNil(o.Client) {
		var ret V0040OpenapiMetaClient
		return ret
	}
	return *o.Client
}

// GetClientOk returns a tuple with the Client field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdJobsRespMeta) GetClientOk() (*V0040OpenapiMetaClient, bool) {
	if o == nil || IsNil(o.Client) {
		return nil, false
	}
	return o.Client, true
}

// HasClient returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdJobsRespMeta) HasClient() bool {
	if o != nil && !IsNil(o.Client) {
		return true
	}

	return false
}

// SetClient gets a reference to the given V0040OpenapiMetaClient and assigns it to the Client field.
func (o *V0041OpenapiSlurmdbdJobsRespMeta) SetClient(v V0040OpenapiMetaClient) {
	o.Client = &v
}

// GetCommand returns the Command field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdJobsRespMeta) GetCommand() []string {
	if o == nil || IsNil(o.Command) {
		var ret []string
		return ret
	}
	return o.Command
}

// GetCommandOk returns a tuple with the Command field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdJobsRespMeta) GetCommandOk() ([]string, bool) {
	if o == nil || IsNil(o.Command) {
		return nil, false
	}
	return o.Command, true
}

// HasCommand returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdJobsRespMeta) HasCommand() bool {
	if o != nil && !IsNil(o.Command) {
		return true
	}

	return false
}

// SetCommand gets a reference to the given []string and assigns it to the Command field.
func (o *V0041OpenapiSlurmdbdJobsRespMeta) SetCommand(v []string) {
	o.Command = v
}

// GetSlurm returns the Slurm field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdJobsRespMeta) GetSlurm() V0040OpenapiMetaSlurm {
	if o == nil || IsNil(o.Slurm) {
		var ret V0040OpenapiMetaSlurm
		return ret
	}
	return *o.Slurm
}

// GetSlurmOk returns a tuple with the Slurm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdJobsRespMeta) GetSlurmOk() (*V0040OpenapiMetaSlurm, bool) {
	if o == nil || IsNil(o.Slurm) {
		return nil, false
	}
	return o.Slurm, true
}

// HasSlurm returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdJobsRespMeta) HasSlurm() bool {
	if o != nil && !IsNil(o.Slurm) {
		return true
	}

	return false
}

// SetSlurm gets a reference to the given V0040OpenapiMetaSlurm and assigns it to the Slurm field.
func (o *V0041OpenapiSlurmdbdJobsRespMeta) SetSlurm(v V0040OpenapiMetaSlurm) {
	o.Slurm = &v
}

func (o V0041OpenapiSlurmdbdJobsRespMeta) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0041OpenapiSlurmdbdJobsRespMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Plugin) {
		toSerialize["plugin"] = o.Plugin
	}
	if !IsNil(o.Client) {
		toSerialize["client"] = o.Client
	}
	if !IsNil(o.Command) {
		toSerialize["command"] = o.Command
	}
	if !IsNil(o.Slurm) {
		toSerialize["slurm"] = o.Slurm
	}
	return toSerialize, nil
}

type NullableV0041OpenapiSlurmdbdJobsRespMeta struct {
	value *V0041OpenapiSlurmdbdJobsRespMeta
	isSet bool
}

func (v NullableV0041OpenapiSlurmdbdJobsRespMeta) Get() *V0041OpenapiSlurmdbdJobsRespMeta {
	return v.value
}

func (v *NullableV0041OpenapiSlurmdbdJobsRespMeta) Set(val *V0041OpenapiSlurmdbdJobsRespMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableV0041OpenapiSlurmdbdJobsRespMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableV0041OpenapiSlurmdbdJobsRespMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0041OpenapiSlurmdbdJobsRespMeta(val *V0041OpenapiSlurmdbdJobsRespMeta) *NullableV0041OpenapiSlurmdbdJobsRespMeta {
	return &NullableV0041OpenapiSlurmdbdJobsRespMeta{value: val, isSet: true}
}

func (v NullableV0041OpenapiSlurmdbdJobsRespMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0041OpenapiSlurmdbdJobsRespMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


